// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-my-rides.ts
import { createClient } from "npm:@supabase/supabase-js@^2.88.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_rides_default = defineTool({
  name: "list_my_rides",
  title: "Zoznam mojich j\xE1zd (vodi\u010D)",
  description: "Vr\xE1ti jazdy, ktor\xE9 signed-in pou\u017E\xEDvate\u013E vytvoril ako vodi\u010D (akt\xEDvne, prebiehaj\xFAce, dokon\u010Den\xE9). Zoraden\xE9 od najnov\u0161\xEDch.",
  inputSchema: {
    status: z.enum(["active", "in_progress", "completed", "cancelled", "all"]).optional().describe("Filter pod\u013Ea stavu jazdy. Predvolen\xE9: all."),
    limit: z.number().int().min(1).max(50).optional().describe("Max po\u010Det z\xE1znamov. Predvolen\xE9: 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nie ste prihl\xE1sen\xFD." }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data: profile } = await sb.from("profiles").select("id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (!profile) {
      return { content: [{ type: "text", text: "Profil sa nena\u0161iel." }], isError: true };
    }
    let q = sb.from("rides").select("id, origin_address, destination_address, departure_time, price_per_seat, seats_available, status").eq("driver_id", profile.id).order("departure_time", { ascending: false }).limit(limit ?? 20);
    if (status && status !== "all") q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rides: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-trips.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.88.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_trips_default = defineTool2({
  name: "list_my_trips",
  title: "Zoznam mojich ciest (spolujazdec)",
  description: "Vr\xE1ti \u017Eiadosti o jazdu (ride_requests), kde signed-in pou\u017E\xEDvate\u013E vystupuje ako spolujazdec.",
  inputSchema: {
    status: z2.enum(["pending", "accepted", "driver_arrived", "picked_up", "completed", "cancelled", "rejected", "all"]).optional().describe("Filter pod\u013Ea stavu \u017Eiadosti. Predvolen\xE9: all."),
    limit: z2.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nie ste prihl\xE1sen\xFD." }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const { data: profile } = await sb.from("profiles").select("id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (!profile) {
      return { content: [{ type: "text", text: "Profil sa nena\u0161iel." }], isError: true };
    }
    let q = sb.from("ride_requests").select("id, ride_id, status, pickup_address, dropoff_address, amount_paid, payment_status, created_at").eq("passenger_id", profile.id).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status && status !== "all") q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { trips: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-rides.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.88.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_rides_default = defineTool3({
  name: "search_rides",
  title: "Vyh\u013Eada\u0165 dostupn\xE9 jazdy",
  description: "Vyh\u013Ead\xE1 akt\xEDvne a prebiehaj\xFAce jazdy pod\u013Ea mesta p\xF4vodu a cie\u013Ea (case-insensitive substring). Vr\xE1ti a\u017E 20 j\xE1zd zoraden\xFDch pod\u013Ea \u010Dasu odchodu.",
  inputSchema: {
    origin: z3.string().min(2).describe("Mesto alebo \u010Das\u0165 adresy p\xF4vodu, napr. 'Bratislava'."),
    destination: z3.string().min(2).describe("Mesto alebo \u010Das\u0165 adresy cie\u013Ea, napr. 'Ko\u0161ice'."),
    max_price: z3.number().positive().optional().describe("Maxim\xE1lna cena za miesto v EUR.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ origin, destination, max_price }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nie ste prihl\xE1sen\xFD." }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    let q = sb.from("rides").select("id, origin_address, destination_address, departure_time, price_per_seat, seats_available, status").in("status", ["active", "in_progress"]).ilike("origin_address", `%${origin}%`).ilike("destination_address", `%${destination}%`).gt("seats_available", 0).order("departure_time", { ascending: true }).limit(20);
    if (max_price) q = q.lte("price_per_seat", max_price);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rides: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.88.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool4({
  name: "get_my_profile",
  title: "M\xF4j profil",
  description: "Vr\xE1ti z\xE1kladn\xE9 \xFAdaje profilu prihl\xE1sen\xE9ho pou\u017E\xEDvate\u013Ea TakeMe: meno, hodnotenie, po\u010Det j\xE1zd, vybran\xE1 rola.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nie ste prihl\xE1sen\xFD." }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    const { data, error } = await sb.from("profiles").select("id, full_name, rating, total_rides, selected_role, bio").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Profil sa nena\u0161iel." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cufiyqtmfpwnogxtgrru";
var mcp_default = defineMcp({
  name: "takeme-mcp",
  title: "TakeMe",
  version: "0.1.0",
  instructions: "TakeMe je slovensk\xE1 platforma na zdie\u013Eanie j\xE1zd (BlaBlaCar-style). Pou\u017Ei tieto n\xE1stroje na h\u013Eadanie j\xE1zd, prezeranie svojich j\xE1zd/ciest a profilu prihl\xE1sen\xE9ho pou\u017E\xEDvate\u013Ea. V\u0161etky n\xE1stroje pracuj\xFA v mene aktu\xE1lneho pou\u017E\xEDvate\u013Ea a re\u0161pektuj\xFA RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_rides_default, list_my_rides_default, list_my_trips_default, get_my_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
